name: "R2 to GitHub"
description: "Transfer files from Cloudflare R2 to GitHub repositories based on size or quantity strategy."
author: "fscarmen2"
inputs:
  config_path:
    description: "Path to the configuration YAML file."
    required: true
    default: "./config.yml"
outputs:
  result:
    description: "Summary of the action's execution."

runs:
  using: composite
  steps:
    - name: Runing
      run: |
        echo "开始 R2 ---> GitHub 脚本"

        # 读取配置文件内容并替换格式，确保冒号后有空格
        CONFIG=$(sed 's/[<>]//g; s/:/: /g; s/:[[:space:]]\+/: /g' "${{ inputs.config_path }}")

        # 从配置文件中读取 Cloudflare R2 的相关参数
        R2_ACCOUNT_NAME=($(yq '.r2_accounts[].name' <<< "$CONFIG")) # 获取所有 R2 的账户名称
        R2_ACCOUNT_ID=($(yq '.r2_accounts[].account_id' <<< "$CONFIG")) # 获取所有 R2 的账户 ID
        R2_ACCESS_KEY_ID=($(yq '.r2_accounts[].access_key_id' <<< "$CONFIG")) # 获取所有 R2 的访问密钥 ID
        R2_SECRET_ACCESS_KEY=($(yq '.r2_accounts[].secret_access_key' <<< "$CONFIG")) # 获取所有 R2 的访问密钥
        R2_BUCKET=($(yq '.r2_accounts[].bucket' <<< "$CONFIG")) # 获取所有 R2 的存储桶名称
        R2_DIR=($(yq '.r2_accounts[].dir' <<< "$CONFIG")) # 获取所有 R2 的文件目录
        for o in "${R2_ACCOUNT_ID[@]}"; do
          R2_ENDPOINT_URL+=(https://${o}.r2.cloudflarestorage.com) # 为每个账户生成对应的 endpoint URL
        done

        # 从配置文件中读取 GitHub 的相关参数
        GITHUB_PAT=$(yq '.github_pat' <<< "$CONFIG")
        GITHUB_REPO_PREFIX=$(yq '.github_repo_prefix' <<< "$CONFIG")
        # 获取 GitHub 的仓库列表
        GITHUB_REPO_LIST=($(yq '.gitlab_pats | keys | .[]' <<< "$CONFIG" | sed "s/^/${GITHUB_REPO_PREFIX}&/g"))
        # 获取 GitHub 用户名
        GITHUB_USERNAME=$(curl --silent --header "Authorization: Bearer $GITHUB_PAT" https://api.github.com/user | awk -F '"' '/"login":/{print $4}')

        # 获取迁移策略
        STRATEGY=$(yq '.strategy' <<< "$CONFIG")

        # 判断是否需要删除已迁移文件
        DELETE=$(yq '.delete' <<< "$CONFIG")

        # 检查策略是否直接指定了仓库
        for j in ${GITHUB_REPO_LIST[@]}; do
          grep -qw "${STRATEGY}" <<< "$j" && REPO_NAME="${STRATEGY}" && break
        done

        # 如果策略直接指定了仓库
        if [ -n "$REPO_NAME" ]; then
          STRATEGY_RESULT="策略: 指定存放到 ${REPO_NAME}" # 策略为指定仓库
        # 如果策略是基于文件数量的最少策略
        elif [ "${STRATEGY,,}" = 'quantity' ]; then
          MIN_INDEX=0
          MIN_FILE_QUANTITY=$(curl --silent \
          --header "Authorization: token ${GITHUB_PAT}" \
          --header "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${GITHUB_USERNAME}/${GITHUB_REPO_LIST[0]}/contents/${R2_DIR} | grep -c '"name"') # 获取第一个仓库的文件数量

          # 遍历仓库，找到文件数量最少的仓库
          for ((i=1; i<${#GITHUB_REPO_LIST[@]}; i++)); do
            REPO_FILE_QUANTITY[i]=$(curl --silent \
            --header "Authorization: token ${GITHUB_PAT}" \
            --header "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${GITHUB_USERNAME}/${GITHUB_REPO_LIST[i]}/contents/${R2_DIR} | grep -c '"name"') # 获取其他仓库的文件数量
            if [[ "$MIN_FILE_QUANTITY" -gt "${REPO_FILE_QUANTITY[i]}" ]]; then
              MIN_FILE_QUANTITY="${REPO_FILE_QUANTITY[i]}"
              MIN_INDEX="$i"
            fi
          done
          REPO_NAME=${GITHUB_REPO_LIST[MIN_INDEX]}
          STRATEGY_RESULT="策略: 存放到文件数量最少的 ${REPO_NAME}" # 选择文件数量最少的仓库
        else
          # 如果策略是基于仓库大小的最小策略
          grep -qwE 'size|quantity' <<< "${STRATEGY,,}" || echo "Strategy 现在 [${STRATEGY}] 不可用， 将采用默认策略 size，可选项是 [size|quantity|$(sed 's/ /|/g' <<< "${GITHUB_REPO_LIST[@]}")]"
          MIN_INDEX=0
          MIN_REPO_SIZE=$(curl --silent \
          --header "Authorization: token ${GITHUB_PAT}" \
          --header "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${GITHUB_USERNAME}/${GITHUB_REPO_LIST[0]}/contents/${R2_DIR} | awk -F '[:,]' '/"size":/{print $2}' | awk '{s+=$1} END {print s}') # 获取第一个仓库的大小

          # 遍历仓库，找到容量最小的仓库
          for ((i=1; i<${#GITHUB_REPO_LIST[@]}; i++)); do
            REPO_SIZE[i]=$(curl --silent --header "Authorization: token ${GITHUB_PAT}" \
            --header "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${GITHUB_USERNAME}/${GITHUB_REPO_LIST[i]}/contents/${R2_DIR} | awk -F '[:,]' '/"size":/{print $2}' | awk '{s+=$1} END {print s}') # 获取其他仓库的大小
            if [[ "$MIN_REPO_SIZE" -gt "${REPO_SIZE[i]}" ]]; then
              MIN_REPO_SIZE="${REPO_SIZE[i]}"
              MIN_INDEX="$i"
            fi
          done
          REPO_NAME=${GITHUB_REPO_LIST[MIN_INDEX]}
          STRATEGY_RESULT="策略: 存放到仓库容量最少的 ${REPO_NAME}" # 选择容量最小的仓库
        fi

        # 提交更改到 GitHub
        git config --global user.name 'github-actions' # 设置 Git 用户名
        git config --global user.email 'github-actions@github.com' # 设置 Git 用户邮箱


        # 配置 AWS CLI 访问 Cloudflare R2 的凭据
        aws configure set region auto # 配置默认区域
        aws configure set output json # 设置输出格式为 JSON

        for n in ${!R2_ACCOUNT_NAME[@]}; do
          aws configure set aws_access_key_id ${R2_ACCESS_KEY_ID[n]}
          aws configure set aws_secret_access_key ${R2_SECRET_ACCESS_KEY[n]}

          # 获取 Cloudflare R2 中的所有文件列表
          unset FILE_LIST SUCCESS_UPDATE NEED_MOVE_FILE SKIP_FILE DELETE_FILE m
          FILE_LIST=($(aws s3 ls --endpoint-url=${R2_ENDPOINT_URL[n]} s3://${R2_BUCKET[n]}/ --recursive | awk '{print $NF}'))

          # 如果有文件需要处理
          if [ "${#FILE_LIST[@]}" -gt 0 ]; then

            # 克隆目标仓库
            [ -d "${REPO_NAME}" ] || git clone --depth=1 https://${GITHUB_USERNAME}:${GITHUB_PAT}@github.com/${GITHUB_USERNAME}/${REPO_NAME}.git
            cd ${REPO_NAME}

            # 遍历文件列表，检查每个文件的大小
            for k in "${FILE_LIST[@]}"; do
              unset FILE_SIZE
              FILE_SIZE=$(aws s3api head-object \
                  --endpoint-url="${R2_ENDPOINT_URL[n]}" \
                  --bucket "${R2_BUCKET[n]}" \
                  --key "${k}" \
                  --query "ContentLength" \
                  --output text)
              # 文件小于等于 100MB 的加入迁移列表
              [ "${FILE_SIZE}" -le 104857600 ] && NEED_MOVE_FILE+=(${k}) || SKIP_FILE+=(${k})
            done

            # 将符合条件的文件下载到本地
            [ "${#NEED_MOVE_FILE}" -gt 0 ] && echo "================================="
            for l in "${NEED_MOVE_FILE[@]}"; do
              (( m++ )) || true
              echo "${R2_ACCOUNT_NAME[n]} copying ${m} / ${#NEED_MOVE_FILE[@]} : ${l#*/}"
              aws s3 cp --endpoint-url=${R2_ENDPOINT_URL[n]} s3://${R2_BUCKET[n]}/${l} ${l} >/dev/null
              DELETE_FILE+=("--include \"${l}\"")
            done

            # 提交更改到 GitHub
            git add .
            git commit -m "Add images from Cloudflare R2 ${R2_ACCOUNT_NAME[n]}" || echo "No changes to commit"
            git push -f && SUCCESS_UPDATE=true || echo "No changes to push"
            cd ..

            if [ "${SUCCESS_UPDATE}" = 'true' ]; then
              # 删除已经迁移的文件
              if [ "${DELETE,,}" = 'true' ]; then
                COPY_OR_MOVE='迁移'
                echo "Delete files from CloudFlare R2 ${R2_ACCOUNT_NAME[n]}"
                aws s3 rm --endpoint-url=${R2_ENDPOINT_URL[n]} s3://${R2_BUCKET[n]} --recursive --exclude "*" $(eval echo "${DELETE_FILE[@]}")
              else
                COPY_OR_MOVE='复制'
              fi

              REPORT+="\n已成功${COPY_OR_MOVE} CloudFlare R2 ${R2_ACCOUNT_NAME[n]} ${#NEED_MOVE_FILE[@]} 个文件 ---> ${REPO_NAME}"
              if [ "${#SKIP_FILE[@]}" -gt 0 ]; then
                [ "${#SKIP_FILE[@]}" = 1 ] && REPORT+="\n1 个文件大于 100MB，不能${COPY_OR_MOVE}到 ${REPO_NAME}，是 ${SKIP_FILE[@]}" || REPORT+="\n${#SKIP_FILE[@]} 个文件大于 100MB，不能${COPY_OR_MOVE}到 ${REPO_NAME}，分别是 ${SKIP_FILE[@]}"
              fi
            else
              REPORT+="\nGitHub: ${REPO_NAME} 更新失败"
            fi
          else
            # 如果没有文件需要处理
            REPORT+="\nCloudFlare R2 ${R2_ACCOUNT_NAME[n]} 没有更新文件."
          fi
        done

        # 本地删除节点仓库
        [ -d "${REPO_NAME}" ] && rm -rf "${REPO_NAME}"

        # 打印总结
        echo "================================="
        echo "总结:"
        echo "${STRATEGY_RESULT}"
        echo -e "${REPORT}"

      shell: bash